import React, { useState } from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Divider from '../components/Divider'
import Menu from '../components/Menu'
import ImgSection from '../components/ImgSection'
import Footer from '../components/Footer'

export const langContext = React.createContext()

export default function Home() {
  const [isEn, setIsEn] = useState(false)

  function updateLang() {
    setIsEn((isEn) => !isEn)
  }
  return (
    <langContext.Provider value={{ isEn, updateLang }}>
      <div className="overflow-x-hidden">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-screen flex lg:flex-row flex-col ">
          <Header />
          <main className="flex flex-col justify-center items-center">
            <Hero />
            <About />
            <Menu />
            {/* <ImgSection /> */}
            <Footer />
          </main>
        </div>
      </div>
    </langContext.Provider>
  )
}
